version: '3.8'  # Atualize a versão do compose para suportar `init` containers
services:
  init-db:
    image: guacamole/guacamole:1.5.5
    command: /opt/guacamole/bin/initdb.sh --mysql > /docker-entrypoint-initdb.d/initdb.sql
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    entrypoint: ["sh", "-c", "mkdir -p /docker-entrypoint-initdb.d && /opt/guacamole/bin/initdb.sh --mysql > /docker-entrypoint-initdb.d/initdb.sql"]

  guacdb:
    container_name: guacamoledb
    image: mariadb:10.11.9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'MariaDBRootPass'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user'
      MYSQL_PASSWORD: 'MariaDBUserPass'
    volumes:
      - './db-data:/var/lib/mysql'
      - './init-scripts:/docker-entrypoint-initdb.d'
    depends_on:
      - init-db  # Garante que o script seja gerado antes do MariaDB iniciar

  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.5
    restart: unless-stopped

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacdb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "MariaDBUserPass"
      TOTP_ENABLED: "true"
    depends_on:
      - guacdb
      - guacd
volumes:
  db-data:
  init-scripts:

