services:
  guacdb:
    container_name: guacamoledb
    image: mariadb:10.11.9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'MariaDBRootPass'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user'
      MYSQL_PASSWORD: 'MariaDBUserPass'
    volumes:
      - './db-data:/var/lib/mysql'
      - './init-scripts:/docker-entrypoint-initdb.d'
    networks:
      - guacamole_network

  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
    networks:
      - guacamole_network

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacamoledb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "MariaDBUserPass"
      TOTP_ENABLED: "true"
    depends_on:
      - guacdb
      - guacd
    expose:
      - 8080
    networks:
      - guacamole_network

  nginx:
    image: nginx:alpine
    container_name: guacamole-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - guacamole
    networks:
      - guacamole_network

networks:
  guacamole_network:
    driver: bridge
